### PR TITLE
Add Try-Catch hacks and tests

### PR DESCRIPTION
**Pull request by B1tF8er**
#5

### CODE REVIEW

**Comment by B1tF8er** [comment]
@madSimonJ Hello, could you review this PR?

**Comment by madSimonJ** [comment]
Thanks for these.  Would you mind amending them though, to use Extension methods and FluentAssertions in the unit tests?  Thanks!

**Comment by madSimonJ** [comment]
> @madSimonJ Hello, could you review this PR?

Sorry for the delay :( I've been really busy this week

**Comment by B1tF8er** [comment]
@madSimonJ No worries, I updated the unit tests to use FluentAssertions

**Comment by B1tF8er** [comment]
@madSimonJ what do you think now?

**Comment by madSimonJ** [comment]
> @madSimonJ what do you think now?

Looks good

**Pull request merged**
